services:
  hospital.healpoint.nl: &hospital
    build:
      context: .
      dockerfile: Dockerfile
    image: medtechchain/hospital
    container_name: hospital.healpoint.nl
    environment: &env
      HOSPITAL_NAME: HealPoint
      CHANNEL_NAME: medtechchain
      CHAINCODE_NAME: medtechchain
      DEVICE_DATA_CONTRACT_NAME: devicedata
      CONFIG_CONTRACT_NAME: platformconfig
      CRYPTO_PATH: /crypto/hospital.healpoint.nl
      CERT_DIR_PATH: ./msp/signcerts
      KEY_DIR_PATH: ./msp/keystore
      TLS_CERT_PATH: ./tls/ca.crt
      MSP_ID: HealPointPeerMSP
      OVERRIDE_AUTH: peer0.healpoint.nl
      PEER_ENDPOINT: peer0.healpoint.nl:7051
    ports:
      - "8081:8080"
    networks:
      - healpoint

  hospital.lifecare.nl:
    <<: *hospital
    container_name: hospital.lifecare.nl
    environment:
      <<: *env
      CRYPTO_PATH: /crypto/hospital.lifecare.nl
      MSP_ID: LifeCarePeerMSP
      OVERRIDE_AUTH: peer0.lifecare.nl
      PEER_ENDPOINT: peer0.lifecare.nl:7051
    ports:
      - "8082:8080"
    networks:
      - lifecare

networks:
  healpoint:
    external: true
    name: healpoint
  lifecare:
    external: true
    name: lifecare